/**
 * Seed script: Populates Firestore `exercises/` collection with ~65 curated exercises.
 * Idempotent — safe to re-run (uses merge: true).
 *
 * Usage: node server/scripts/seedExercises.js
 */
const admin = require('firebase-admin');

if (!admin.apps.length) {
  admin.initializeApp({ credential: admin.credential.applicationDefault() });
}
const db = admin.firestore();

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

const exercises = [
  // ── Push (15) ──
  { name: 'Barbell Bench Press', category: 'Push', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: ['barbell', 'bench'], difficulty: 'intermediate', instructions: ['Lie flat on a bench with feet on the floor.', 'Grip the bar slightly wider than shoulder-width.', 'Unrack and lower the bar to mid-chest.', 'Press the bar back up to lockout.'], tips: ['Keep your shoulder blades retracted.', 'Drive your feet into the floor for stability.'], alternatives: ['dumbbell-bench-press', 'machine-chest-press'], tags: ['compound', 'strength', 'chest'] },
  { name: 'Dumbbell Bench Press', category: 'Push', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: ['dumbbells', 'bench'], difficulty: 'beginner', instructions: ['Lie on a flat bench holding dumbbells at chest level.', 'Press the dumbbells up until arms are extended.', 'Lower slowly back to starting position.'], tips: ['Squeeze your chest at the top.', 'Keep a slight arch in your lower back.'], alternatives: ['barbell-bench-press', 'machine-chest-press'], tags: ['compound', 'strength', 'chest'] },
  { name: 'Incline Dumbbell Press', category: 'Push', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders', 'Triceps'], equipment: ['dumbbells', 'bench'], difficulty: 'intermediate', instructions: ['Set bench to 30-45 degree incline.', 'Press dumbbells up from shoulder level.', 'Lower with control.'], tips: ['Keep elbows at roughly 45 degrees.', 'Focus on upper chest squeeze.'], alternatives: ['incline-barbell-press', 'cable-chest-fly'], tags: ['compound', 'strength', 'upper chest'] },
  { name: 'Incline Barbell Press', category: 'Push', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders', 'Triceps'], equipment: ['barbell', 'bench'], difficulty: 'intermediate', instructions: ['Set bench to 30-45 degree incline.', 'Unrack barbell and lower to upper chest.', 'Press back up to lockout.'], tips: ['Keep wrists stacked over elbows.', 'Do not flare elbows excessively.'], alternatives: ['incline-dumbbell-press', 'cable-chest-fly'], tags: ['compound', 'strength', 'upper chest'] },
  { name: 'Overhead Press', category: 'Push', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps', 'Core'], equipment: ['barbell'], difficulty: 'intermediate', instructions: ['Stand with the bar at shoulder height.', 'Brace your core and press overhead.', 'Lock out at the top, then lower slowly.'], tips: ['Keep your ribs down — avoid arching your back.', 'Push your head through once the bar passes your forehead.'], alternatives: ['dumbbell-shoulder-press', 'arnold-press'], tags: ['compound', 'strength', 'shoulders'] },
  { name: 'Dumbbell Shoulder Press', category: 'Push', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: ['Sit or stand with dumbbells at shoulder height.', 'Press up until arms are fully extended.', 'Lower to starting position with control.'], tips: ['Keep core braced throughout.', 'Don\'t lock elbows aggressively at the top.'], alternatives: ['overhead-press', 'arnold-press'], tags: ['compound', 'strength', 'shoulders'] },
  { name: 'Arnold Press', category: 'Push', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], equipment: ['dumbbells'], difficulty: 'intermediate', instructions: ['Start with dumbbells at chin level, palms facing you.', 'Rotate palms outward as you press overhead.', 'Reverse the motion on the way down.'], tips: ['Use a smooth rotation — don\'t rush.', 'Keep the movement controlled.'], alternatives: ['dumbbell-shoulder-press', 'overhead-press'], tags: ['compound', 'strength', 'shoulders'] },
  { name: 'Dips', category: 'Push', primaryMuscles: ['Chest', 'Triceps'], secondaryMuscles: ['Shoulders'], equipment: ['dip bars'], difficulty: 'intermediate', instructions: ['Grip the dip bars and lift yourself up.', 'Lower your body by bending the elbows.', 'Push back up to the starting position.'], tips: ['Lean forward to target chest, stay upright for triceps.', 'Go to at least 90-degree elbow bend.'], alternatives: ['close-grip-bench-press', 'tricep-pushdowns'], tags: ['compound', 'bodyweight', 'chest', 'triceps'] },
  { name: 'Close-Grip Bench Press', category: 'Push', primaryMuscles: ['Triceps'], secondaryMuscles: ['Chest', 'Shoulders'], equipment: ['barbell', 'bench'], difficulty: 'intermediate', instructions: ['Lie on a bench with a narrow grip (shoulder-width).', 'Lower the bar to your lower chest.', 'Press up, focusing on tricep engagement.'], tips: ['Keep elbows close to your body.', 'Don\'t go too narrow — shoulder-width is enough.'], alternatives: ['dips', 'tricep-pushdowns'], tags: ['compound', 'strength', 'triceps'] },
  { name: 'Tricep Pushdowns', category: 'Push', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: ['cable machine'], difficulty: 'beginner', instructions: ['Stand facing a cable machine with a straight or rope attachment.', 'Push the handle down until arms are fully extended.', 'Slowly return to starting position.'], tips: ['Keep elbows pinned to your sides.', 'Squeeze your triceps at the bottom.'], alternatives: ['overhead-tricep-extension', 'dips'], tags: ['isolation', 'strength', 'triceps'] },
  { name: 'Overhead Tricep Extension', category: 'Push', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: ['dumbbell'], difficulty: 'beginner', instructions: ['Hold a dumbbell overhead with both hands.', 'Lower it behind your head by bending elbows.', 'Extend arms back to the top.'], tips: ['Keep upper arms close to your head.', 'Use a controlled tempo.'], alternatives: ['tricep-pushdowns', 'skull-crushers'], tags: ['isolation', 'strength', 'triceps'] },
  { name: 'Skull Crushers', category: 'Push', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: ['ez-bar', 'bench'], difficulty: 'intermediate', instructions: ['Lie on a bench holding an EZ-bar above your chest.', 'Lower the bar toward your forehead by bending elbows.', 'Extend back to the starting position.'], tips: ['Keep upper arms stationary.', 'Don\'t let the bar drift back too far.'], alternatives: ['overhead-tricep-extension', 'tricep-pushdowns'], tags: ['isolation', 'strength', 'triceps'] },
  { name: 'Lateral Raises', category: 'Push', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: ['dumbbells'], difficulty: 'beginner', instructions: ['Stand holding dumbbells at your sides.', 'Raise arms out to the side until parallel with the floor.', 'Lower slowly back down.'], tips: ['Lead with your elbows, not your hands.', 'Use a slight bend in the elbows.'], alternatives: ['cable-lateral-raises', 'machine-lateral-raises'], tags: ['isolation', 'shoulders'] },
  { name: 'Cable Chest Fly', category: 'Push', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], equipment: ['cable machine'], difficulty: 'beginner', instructions: ['Set cables to shoulder height and grab handles.', 'Step forward, bring hands together in front of chest.', 'Slowly return to starting position.'], tips: ['Keep a slight bend in your elbows.', 'Focus on squeezing your chest.'], alternatives: ['dumbbell-bench-press', 'machine-chest-press'], tags: ['isolation', 'chest'] },
  { name: 'Machine Chest Press', category: 'Push', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: ['machine'], difficulty: 'beginner', instructions: ['Sit in the machine with handles at chest height.', 'Push handles forward until arms are extended.', 'Return with control.'], tips: ['Adjust the seat so handles align with mid-chest.', 'Great for beginners or burnout sets.'], alternatives: ['barbell-bench-press', 'dumbbell-bench-press'], tags: ['compound', 'machine', 'chest'] },

  // ── Pull (15) ──
  { name: 'Pull-Ups', category: 'Pull', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps', 'Forearms'], equipment: ['pull-up bar'], difficulty: 'intermediate', instructions: ['Hang from a bar with an overhand grip.', 'Pull yourself up until chin clears the bar.', 'Lower with control.'], tips: ['Engage your lats — think "pull elbows to hips".', 'Avoid swinging or kipping.'], alternatives: ['lat-pulldown', 'assisted-pull-ups'], tags: ['compound', 'bodyweight', 'back'] },
  { name: 'Lat Pulldown', category: 'Pull', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps'], equipment: ['cable machine'], difficulty: 'beginner', instructions: ['Sit at a lat pulldown machine and grab the wide bar.', 'Pull the bar down to your upper chest.', 'Slowly return to the top.'], tips: ['Lean back slightly and drive elbows down.', 'Squeeze shoulder blades together at the bottom.'], alternatives: ['pull-ups', 'single-arm-lat-pulldown'], tags: ['compound', 'back'] },
  { name: 'Barbell Row', category: 'Pull', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps', 'Rear Delts'], equipment: ['barbell'], difficulty: 'intermediate', instructions: ['Hinge at the hips with a slight knee bend.', 'Pull the barbell to your lower chest/upper abs.', 'Lower with control.'], tips: ['Keep your back flat — don\'t round.', 'Pull with your elbows, not your hands.'], alternatives: ['dumbbell-row', 'cable-row'], tags: ['compound', 'strength', 'back'] },
  { name: 'Dumbbell Row', category: 'Pull', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps', 'Rear Delts'], equipment: ['dumbbell', 'bench'], difficulty: 'beginner', instructions: ['Place one knee and hand on a bench.', 'Row the dumbbell to your hip with the other arm.', 'Lower with control and repeat.'], tips: ['Keep your torso parallel to the ground.', 'Don\'t rotate your torso to lift the weight.'], alternatives: ['barbell-row', 'cable-row'], tags: ['compound', 'back'] },
  { name: 'Cable Row', category: 'Pull', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps'], equipment: ['cable machine'], difficulty: 'beginner', instructions: ['Sit at a cable row station with feet on the platform.', 'Pull the handle to your lower chest.', 'Slowly extend arms back.'], tips: ['Keep your chest up and back straight.', 'Squeeze shoulder blades at the end of the pull.'], alternatives: ['barbell-row', 'dumbbell-row'], tags: ['compound', 'back'] },
  { name: 'T-Bar Row', category: 'Pull', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps', 'Rear Delts'], equipment: ['t-bar', 'barbell'], difficulty: 'intermediate', instructions: ['Straddle the t-bar or landmine.', 'Hinge at the hips and grab the handle.', 'Row to your chest, squeeze, and lower.'], tips: ['Keep knees slightly bent.', 'Avoid using momentum.'], alternatives: ['barbell-row', 'dumbbell-row'], tags: ['compound', 'strength', 'back'] },
  { name: 'Face Pulls', category: 'Pull', primaryMuscles: ['Rear Delts'], secondaryMuscles: ['Rotator Cuff', 'Traps'], equipment: ['cable machine'], difficulty: 'beginner', instructions: ['Set cable to face height with a rope attachment.', 'Pull the rope toward your face, separating the ends.', 'Squeeze rear delts and slowly return.'], tips: ['Keep elbows high throughout.', 'Great for shoulder health and posture.'], alternatives: ['reverse-fly', 'band-pull-aparts'], tags: ['isolation', 'shoulders', 'back'] },
  { name: 'Reverse Fly', category: 'Pull', primaryMuscles: ['Rear Delts'], secondaryMuscles: ['Traps'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: ['Hinge forward at the hips holding dumbbells.', 'Raise arms out to the sides.', 'Lower with control.'], tips: ['Keep a slight bend in the elbows.', 'Focus on squeezing shoulder blades together.'], alternatives: ['face-pulls', 'cable-reverse-fly'], tags: ['isolation', 'shoulders'] },
  { name: 'Barbell Curl', category: 'Pull', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: ['barbell'], difficulty: 'beginner', instructions: ['Stand holding a barbell with an underhand grip.', 'Curl the bar up to shoulder level.', 'Lower with control.'], tips: ['Keep elbows pinned to your sides.', 'Don\'t swing the weight — strict form.'], alternatives: ['dumbbell-curl', 'ez-bar-curl'], tags: ['isolation', 'strength', 'biceps'] },
  { name: 'Dumbbell Curl', category: 'Pull', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: ['Stand with dumbbells at your sides, palms forward.', 'Curl one or both dumbbells up.', 'Lower slowly.'], tips: ['Supinate (rotate) your wrist as you curl for peak contraction.', 'Don\'t use body momentum.'], alternatives: ['barbell-curl', 'hammer-curl'], tags: ['isolation', 'biceps'] },
  { name: 'Hammer Curl', category: 'Pull', primaryMuscles: ['Biceps'], secondaryMuscles: ['Brachioradialis', 'Forearms'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: ['Stand with dumbbells at your sides, palms facing each other.', 'Curl up while keeping neutral grip.', 'Lower with control.'], tips: ['Great for building forearm and brachialis size.', 'Keep elbows stationary.'], alternatives: ['dumbbell-curl', 'barbell-curl'], tags: ['isolation', 'biceps', 'forearms'] },
  { name: 'EZ-Bar Curl', category: 'Pull', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: ['ez-bar'], difficulty: 'beginner', instructions: ['Stand holding an EZ-bar at the angled grips.', 'Curl the bar up to shoulder height.', 'Lower slowly.'], tips: ['The angled grip reduces wrist strain.', 'Great alternative to straight bar curls.'], alternatives: ['barbell-curl', 'dumbbell-curl'], tags: ['isolation', 'biceps'] },
  { name: 'Chin-Ups', category: 'Pull', primaryMuscles: ['Back', 'Biceps'], secondaryMuscles: ['Forearms'], equipment: ['pull-up bar'], difficulty: 'intermediate', instructions: ['Hang from a bar with an underhand (supinated) grip.', 'Pull yourself up until chin clears the bar.', 'Lower with control.'], tips: ['Underhand grip hits biceps more than pull-ups.', 'Full range of motion — dead hang to chin over bar.'], alternatives: ['pull-ups', 'lat-pulldown'], tags: ['compound', 'bodyweight', 'back', 'biceps'] },
  { name: 'Shrugs', category: 'Pull', primaryMuscles: ['Traps'], secondaryMuscles: [], equipment: ['barbell', 'dumbbells'], difficulty: 'beginner', instructions: ['Stand holding heavy weight at your sides.', 'Shrug shoulders straight up toward your ears.', 'Hold briefly and lower.'], tips: ['Don\'t roll your shoulders — straight up and down.', 'Use straps if grip is limiting.'], alternatives: ['face-pulls', 'rack-pulls'], tags: ['isolation', 'traps'] },
  { name: 'Assisted Pull-Ups', category: 'Pull', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps'], equipment: ['assisted pull-up machine'], difficulty: 'beginner', instructions: ['Set the counterweight on the assisted pull-up machine.', 'Kneel on the pad and grab the handles.', 'Pull yourself up until chin clears, then lower slowly.'], tips: ['Progressively reduce the counterweight over time.', 'Focus on the same form as regular pull-ups.'], alternatives: ['lat-pulldown', 'pull-ups'], tags: ['compound', 'back'] },

  // ── Legs (15) ──
  { name: 'Barbell Back Squat', category: 'Legs', primaryMuscles: ['Quadriceps', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Core'], equipment: ['barbell', 'squat rack'], difficulty: 'intermediate', instructions: ['Place the bar on your upper traps.', 'Unrack and step back, feet shoulder-width.', 'Squat down until thighs are parallel or below.', 'Drive up through your heels.'], tips: ['Keep your chest up and core braced.', 'Knees should track over toes.'], alternatives: ['goblet-squat', 'leg-press'], tags: ['compound', 'strength', 'legs'] },
  { name: 'Goblet Squat', category: 'Legs', primaryMuscles: ['Quadriceps', 'Glutes'], secondaryMuscles: ['Core'], equipment: ['dumbbell', 'kettlebell'], difficulty: 'beginner', instructions: ['Hold a dumbbell or kettlebell at chest level.', 'Squat down keeping weight close to your body.', 'Drive up through your heels.'], tips: ['Great for learning squat mechanics.', 'Keep elbows between your knees at the bottom.'], alternatives: ['barbell-back-squat', 'leg-press'], tags: ['compound', 'legs'] },
  { name: 'Romanian Deadlift', category: 'Legs', primaryMuscles: ['Hamstrings', 'Glutes'], secondaryMuscles: ['Lower Back'], equipment: ['barbell'], difficulty: 'intermediate', instructions: ['Stand holding a barbell at hip level.', 'Hinge at the hips, pushing them back.', 'Lower the bar along your legs until you feel a stretch.', 'Drive hips forward to return.'], tips: ['Keep the bar close to your body.', 'Slight knee bend — this is a hip hinge, not a squat.'], alternatives: ['dumbbell-rdl', 'single-leg-rdl'], tags: ['compound', 'strength', 'hamstrings'] },
  { name: 'Dumbbell RDL', category: 'Legs', primaryMuscles: ['Hamstrings', 'Glutes'], secondaryMuscles: ['Lower Back'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: ['Stand holding dumbbells in front of thighs.', 'Hinge at hips, lowering dumbbells along legs.', 'Return to standing by driving hips forward.'], tips: ['Feel the stretch in your hamstrings.', 'Keep back flat throughout.'], alternatives: ['romanian-deadlift', 'single-leg-rdl'], tags: ['compound', 'hamstrings'] },
  { name: 'Leg Press', category: 'Legs', primaryMuscles: ['Quadriceps', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: ['leg press machine'], difficulty: 'beginner', instructions: ['Sit in the leg press with feet shoulder-width on the platform.', 'Lower the weight until knees are at 90 degrees.', 'Press back up without locking knees.'], tips: ['Don\'t let your lower back round off the pad.', 'Foot placement changes muscle emphasis.'], alternatives: ['barbell-back-squat', 'hack-squat'], tags: ['compound', 'machine', 'legs'] },
  { name: 'Hack Squat', category: 'Legs', primaryMuscles: ['Quadriceps'], secondaryMuscles: ['Glutes'], equipment: ['hack squat machine'], difficulty: 'intermediate', instructions: ['Stand in the hack squat machine with shoulders under the pads.', 'Lower your body by bending your knees.', 'Press back up.'], tips: ['Feet lower on the platform targets quads more.', 'Great alternative to free-weight squats.'], alternatives: ['barbell-back-squat', 'leg-press'], tags: ['compound', 'machine', 'legs'] },
  { name: 'Bulgarian Split Squat', category: 'Legs', primaryMuscles: ['Quadriceps', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Core'], equipment: ['dumbbells', 'bench'], difficulty: 'intermediate', instructions: ['Stand with one foot elevated behind you on a bench.', 'Lower your back knee toward the floor.', 'Drive up through your front heel.'], tips: ['Keep your torso upright.', 'Front knee shouldn\'t pass far beyond toes.'], alternatives: ['lunges', 'goblet-squat'], tags: ['compound', 'unilateral', 'legs'] },
  { name: 'Lunges', category: 'Legs', primaryMuscles: ['Quadriceps', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: ['Stand tall holding dumbbells at your sides.', 'Step forward and lower until both knees are at 90 degrees.', 'Push back to starting position.'], tips: ['Take a big enough step to avoid knee strain.', 'Keep your torso upright.'], alternatives: ['bulgarian-split-squat', 'walking-lunges'], tags: ['compound', 'unilateral', 'legs'] },
  { name: 'Hip Thrust', category: 'Legs', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], equipment: ['barbell', 'bench'], difficulty: 'intermediate', instructions: ['Sit on the floor with upper back against a bench.', 'Roll a barbell over your hips.', 'Drive hips up until your body forms a straight line.', 'Lower with control.'], tips: ['Squeeze glutes hard at the top.', 'Keep chin tucked — don\'t hyperextend your back.'], alternatives: ['glute-bridge', 'cable-pull-through'], tags: ['compound', 'strength', 'glutes'] },
  { name: 'Leg Curl', category: 'Legs', primaryMuscles: ['Hamstrings'], secondaryMuscles: [], equipment: ['leg curl machine'], difficulty: 'beginner', instructions: ['Lie face down on the leg curl machine.', 'Curl your heels toward your glutes.', 'Lower slowly.'], tips: ['Don\'t let hips lift off the pad.', 'Control the negative — don\'t let it slam down.'], alternatives: ['romanian-deadlift', 'nordic-curl'], tags: ['isolation', 'machine', 'hamstrings'] },
  { name: 'Leg Extension', category: 'Legs', primaryMuscles: ['Quadriceps'], secondaryMuscles: [], equipment: ['leg extension machine'], difficulty: 'beginner', instructions: ['Sit in the machine with pad on your shins.', 'Extend your legs until straight.', 'Lower with control.'], tips: ['Squeeze your quads at the top.', 'Don\'t use heavy weight with jerky form.'], alternatives: ['goblet-squat', 'barbell-back-squat'], tags: ['isolation', 'machine', 'quadriceps'] },
  { name: 'Calf Raises', category: 'Legs', primaryMuscles: ['Calves'], secondaryMuscles: [], equipment: ['machine', 'dumbbells'], difficulty: 'beginner', instructions: ['Stand on a raised surface with heels hanging off.', 'Rise up onto your toes as high as possible.', 'Lower slowly below the platform for a stretch.'], tips: ['Full range of motion is key.', 'Pause at the top for maximum contraction.'], alternatives: ['seated-calf-raise'], tags: ['isolation', 'calves'] },
  { name: 'Glute Bridge', category: 'Legs', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: ['Lie on your back with knees bent and feet flat.', 'Drive hips up by squeezing glutes.', 'Lower with control.'], tips: ['Great activation exercise for warm-up.', 'Hold at the top for 2 seconds.'], alternatives: ['hip-thrust', 'cable-pull-through'], tags: ['isolation', 'bodyweight', 'glutes'] },
  { name: 'Walking Lunges', category: 'Legs', primaryMuscles: ['Quadriceps', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Core'], equipment: ['dumbbells'], difficulty: 'intermediate', instructions: ['Hold dumbbells at your sides.', 'Step forward into a lunge.', 'Drive off the front foot and step the back foot forward into the next lunge.'], tips: ['Keep your torso tall.', 'Push off the front heel.'], alternatives: ['lunges', 'bulgarian-split-squat'], tags: ['compound', 'unilateral', 'legs'] },
  { name: 'Single-Leg RDL', category: 'Legs', primaryMuscles: ['Hamstrings', 'Glutes'], secondaryMuscles: ['Core', 'Lower Back'], equipment: ['dumbbell'], difficulty: 'intermediate', instructions: ['Stand on one leg holding a dumbbell.', 'Hinge forward while extending the free leg behind you.', 'Return to standing.'], tips: ['Focus on balance and control.', 'Keep hips square — don\'t rotate.'], alternatives: ['romanian-deadlift', 'dumbbell-rdl'], tags: ['compound', 'unilateral', 'hamstrings'] },

  // ── Core (10) ──
  { name: 'Plank', category: 'Core', primaryMuscles: ['Core'], secondaryMuscles: ['Shoulders'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: ['Get into a forearm plank position.', 'Keep your body in a straight line from head to heels.', 'Hold for the prescribed time.'], tips: ['Don\'t let your hips sag or pike up.', 'Squeeze your glutes and brace your core.'], alternatives: ['dead-bug', 'hollow-hold'], tags: ['isometric', 'bodyweight', 'core'] },
  { name: 'Hanging Leg Raises', category: 'Core', primaryMuscles: ['Core'], secondaryMuscles: ['Hip Flexors'], equipment: ['pull-up bar'], difficulty: 'intermediate', instructions: ['Hang from a pull-up bar.', 'Raise your legs until parallel with the floor (or higher).', 'Lower with control.'], tips: ['Avoid swinging — if you swing, bend your knees.', 'Control the negative portion.'], alternatives: ['lying-leg-raises', 'captain-chair-raises'], tags: ['strength', 'core'] },
  { name: 'Cable Crunches', category: 'Core', primaryMuscles: ['Core'], secondaryMuscles: [], equipment: ['cable machine'], difficulty: 'intermediate', instructions: ['Kneel facing a cable machine with rope attachment overhead.', 'Crunch down, bringing elbows toward knees.', 'Return to starting position.'], tips: ['Focus on flexing your spine, not pulling with arms.', 'Keep hips stationary.'], alternatives: ['hanging-leg-raises', 'ab-wheel-rollout'], tags: ['strength', 'core'] },
  { name: 'Ab Wheel Rollout', category: 'Core', primaryMuscles: ['Core'], secondaryMuscles: ['Shoulders', 'Lats'], equipment: ['ab wheel'], difficulty: 'advanced', instructions: ['Kneel holding an ab wheel.', 'Roll out as far as you can while maintaining a flat back.', 'Pull yourself back to the starting position.'], tips: ['Start with short ranges and work up.', 'Keep your core engaged the entire time.'], alternatives: ['plank', 'cable-crunches'], tags: ['strength', 'core'] },
  { name: 'Russian Twist', category: 'Core', primaryMuscles: ['Obliques'], secondaryMuscles: ['Core'], equipment: ['dumbbell', 'medicine ball'], difficulty: 'beginner', instructions: ['Sit with knees bent, leaning back slightly.', 'Hold a weight at chest level.', 'Rotate your torso side to side.'], tips: ['Keep your chest up — don\'t round your back.', 'Twist from your core, not just your arms.'], alternatives: ['woodchop', 'bicycle-crunches'], tags: ['strength', 'core', 'obliques'] },
  { name: 'Bicycle Crunches', category: 'Core', primaryMuscles: ['Core', 'Obliques'], secondaryMuscles: [], equipment: ['bodyweight'], difficulty: 'beginner', instructions: ['Lie on your back with hands behind your head.', 'Bring one knee to opposite elbow while extending the other leg.', 'Alternate sides in a pedaling motion.'], tips: ['Don\'t pull on your neck.', 'Control the movement — don\'t rush.'], alternatives: ['russian-twist', 'lying-leg-raises'], tags: ['bodyweight', 'core'] },
  { name: 'Dead Bug', category: 'Core', primaryMuscles: ['Core'], secondaryMuscles: ['Hip Flexors'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: ['Lie on your back with arms extended up and knees at 90 degrees.', 'Extend opposite arm and leg toward the floor.', 'Return and repeat on the other side.'], tips: ['Keep your lower back pressed into the floor.', 'Great for core stability and warm-up.'], alternatives: ['plank', 'bird-dog'], tags: ['bodyweight', 'core', 'stability'] },
  { name: 'Woodchop', category: 'Core', primaryMuscles: ['Obliques'], secondaryMuscles: ['Core', 'Shoulders'], equipment: ['cable machine', 'medicine ball'], difficulty: 'intermediate', instructions: ['Set a cable or hold a medicine ball at one side.', 'Rotate and pull diagonally across your body.', 'Control the return.'], tips: ['Power comes from your hips and core, not arms.', 'Keep feet planted.'], alternatives: ['russian-twist', 'pallof-press'], tags: ['strength', 'core', 'rotation'] },
  { name: 'Pallof Press', category: 'Core', primaryMuscles: ['Core'], secondaryMuscles: ['Obliques'], equipment: ['cable machine', 'resistance band'], difficulty: 'beginner', instructions: ['Stand perpendicular to a cable or band anchor at chest height.', 'Hold the handle at your chest and press it straight out.', 'Hold for 2-3 seconds and return.'], tips: ['Resist the rotation — that\'s the exercise.', 'Great anti-rotation exercise for core stability.'], alternatives: ['plank', 'dead-bug'], tags: ['stability', 'core', 'anti-rotation'] },
  { name: 'Hollow Hold', category: 'Core', primaryMuscles: ['Core'], secondaryMuscles: ['Hip Flexors'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: ['Lie on your back and lift shoulders and legs off the floor.', 'Extend arms overhead and legs straight.', 'Hold the position.'], tips: ['Press your lower back into the floor.', 'Scale by bending knees or keeping arms at sides.'], alternatives: ['plank', 'dead-bug'], tags: ['isometric', 'bodyweight', 'core'] },

  // ── Compound (5) ──
  { name: 'Deadlift', category: 'Compound', primaryMuscles: ['Back', 'Glutes', 'Hamstrings'], secondaryMuscles: ['Core', 'Traps', 'Forearms'], equipment: ['barbell'], difficulty: 'advanced', instructions: ['Stand with feet hip-width, bar over mid-foot.', 'Hinge down and grip the bar just outside your knees.', 'Brace your core and drive through your heels to stand.', 'Lower the bar by hinging at the hips.'], tips: ['Keep the bar close to your body the entire time.', 'Don\'t round your lower back.', 'Think "push the floor away" rather than pulling the bar.'], alternatives: ['trap-bar-deadlift', 'romanian-deadlift'], tags: ['compound', 'strength', 'full body'] },
  { name: 'Clean and Press', category: 'Compound', primaryMuscles: ['Shoulders', 'Back', 'Legs'], secondaryMuscles: ['Core', 'Triceps'], equipment: ['barbell'], difficulty: 'advanced', instructions: ['Start with the bar on the floor.', 'Clean the bar to your shoulders in one explosive movement.', 'Press the bar overhead.', 'Lower and repeat.'], tips: ['Master the clean and press separately first.', 'Use your legs to generate momentum.'], alternatives: ['overhead-press', 'dumbbell-clean-and-press'], tags: ['compound', 'strength', 'full body', 'power'] },
  { name: 'Thrusters', category: 'Compound', primaryMuscles: ['Quadriceps', 'Shoulders'], secondaryMuscles: ['Glutes', 'Core', 'Triceps'], equipment: ['barbell', 'dumbbells'], difficulty: 'intermediate', instructions: ['Hold the bar at shoulder height in a front squat position.', 'Squat down to parallel.', 'Drive up explosively and press the bar overhead.'], tips: ['Use the momentum from the squat to help the press.', 'Great for conditioning and full-body work.'], alternatives: ['clean-and-press', 'wall-balls'], tags: ['compound', 'conditioning', 'full body'] },
  { name: "Farmer's Walk", category: 'Compound', primaryMuscles: ['Forearms', 'Traps', 'Core'], secondaryMuscles: ['Legs', 'Shoulders'], equipment: ['dumbbells', 'kettlebells'], difficulty: 'beginner', instructions: ['Pick up heavy weights in each hand.', 'Walk with an upright posture for a set distance or time.', 'Set weights down with control.'], tips: ['Keep shoulders packed and down.', 'Squeeze the handles hard.', 'Walk with short, quick steps.'], alternatives: ['suitcase-carry', 'trap-bar-deadlift'], tags: ['compound', 'grip', 'conditioning'] },
  { name: 'Trap Bar Deadlift', category: 'Compound', primaryMuscles: ['Back', 'Glutes', 'Quadriceps'], secondaryMuscles: ['Hamstrings', 'Core', 'Traps'], equipment: ['trap bar'], difficulty: 'intermediate', instructions: ['Stand inside the trap bar with feet hip-width.', 'Hinge down and grab the handles.', 'Drive through your heels to stand.', 'Lower with control.'], tips: ['More quad-dominant than conventional deadlift.', 'Great alternative for those with back issues.'], alternatives: ['deadlift', 'barbell-back-squat'], tags: ['compound', 'strength', 'full body'] },

  // ── Cardio (5) ──
  { name: 'Burpees', category: 'Cardio', primaryMuscles: ['Full Body'], secondaryMuscles: ['Core', 'Chest', 'Legs'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: ['Stand, then drop into a push-up position.', 'Perform a push-up.', 'Jump your feet to your hands.', 'Jump up with arms overhead.'], tips: ['Modify by stepping instead of jumping if needed.', 'Keep a steady pace rather than going all-out.'], alternatives: ['mountain-climbers', 'box-jumps'], tags: ['cardio', 'conditioning', 'bodyweight'] },
  { name: 'Box Jumps', category: 'Cardio', primaryMuscles: ['Quadriceps', 'Glutes'], secondaryMuscles: ['Calves', 'Core'], equipment: ['plyo box'], difficulty: 'intermediate', instructions: ['Stand in front of a box.', 'Swing your arms and jump onto the box.', 'Land softly with bent knees.', 'Step down and repeat.'], tips: ['Start with a lower box and work up.', 'Land quietly — soft landings protect your joints.'], alternatives: ['burpees', 'jump-squats'], tags: ['cardio', 'plyometric', 'power'] },
  { name: 'Jump Rope', category: 'Cardio', primaryMuscles: ['Calves'], secondaryMuscles: ['Shoulders', 'Core'], equipment: ['jump rope'], difficulty: 'beginner', instructions: ['Hold the rope handles at hip height.', 'Swing the rope over your head.', 'Jump just high enough to clear the rope.'], tips: ['Stay on the balls of your feet.', 'Keep jumps small and wrists relaxed.'], alternatives: ['mountain-climbers', 'burpees'], tags: ['cardio', 'conditioning'] },
  { name: 'Mountain Climbers', category: 'Cardio', primaryMuscles: ['Core'], secondaryMuscles: ['Shoulders', 'Hip Flexors'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: ['Start in a push-up position.', 'Drive one knee toward your chest.', 'Quickly switch legs in a running motion.'], tips: ['Keep hips level — don\'t let them pike up.', 'Maintain a fast, controlled pace.'], alternatives: ['burpees', 'high-knees'], tags: ['cardio', 'bodyweight', 'core'] },
  { name: 'Kettlebell Swings', category: 'Cardio', primaryMuscles: ['Glutes', 'Hamstrings'], secondaryMuscles: ['Core', 'Shoulders'], equipment: ['kettlebell'], difficulty: 'intermediate', instructions: ['Stand with feet wider than shoulder-width.', 'Hinge at hips and swing the kettlebell between your legs.', 'Drive hips forward to swing the kettlebell to chest height.', 'Let it swing back and repeat.'], tips: ['This is a hip hinge, not a squat.', 'Power comes from the hips, not the arms.'], alternatives: ['burpees', 'box-jumps'], tags: ['cardio', 'conditioning', 'strength'] },
];

async function seed() {
  console.log(`Seeding ${exercises.length} exercises...`);

  // Batch writes (Firestore limit: 500 per batch)
  let batch = db.batch();
  let count = 0;

  for (const ex of exercises) {
    const id = slug(ex.name);
    const ref = db.collection('exercises').doc(id);
    batch.set(ref, {
      ...ex,
      imageUrl: null,
      gifUrl: null,
      thumbnailUrl: null,
    }, { merge: true });

    count++;
    if (count % 450 === 0) {
      await batch.commit();
      batch = db.batch();
      console.log(`  Committed ${count} exercises...`);
    }
  }

  if (count % 450 !== 0) {
    await batch.commit();
  }

  console.log(`Done! Seeded ${count} exercises.`);
}

seed().catch(err => {
  console.error('Seed failed:', err);
  process.exit(1);
});
